# Assignment 2 — Food-101: baseline vs pretrained ResNet-50

- Dataset: Food-101, 101 classes, 75,750 train / 25,250 official test.
- Models: Assignment 1 CNN baseline, ImageNet ResNet-50 full fine-tune, ResNet-50 frozen backbone.
- Seeds: 42, 67, 69; split fixed at seed 42.
- Metrics: accuracy, macro-F1, per-class F1, training time, inference time.

In [1]:
import sys
from pathlib import Path

REPO_ROOT = Path.cwd().resolve()
while not (REPO_ROOT / "assignment2").exists() and REPO_ROOT != REPO_ROOT.parent:
    REPO_ROOT = REPO_ROOT.parent
sys.path.insert(0, str(REPO_ROOT / "assignment2" / "src"))
sys.path.insert(0, str(REPO_ROOT))

import json
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

from training_loop import evaluate, fit, set_seed
from utils.dataloader import build_food101_loaders
from utils.experiment_utils import measure_inference_time, plot_curves, plot_examples
from models.baseline import build_baseline_cnn
from models.resnet import build_resnet50

SEEDS = [42, 67, 69]
SPLIT_SEED = 42
EPOCHS = 30
BATCH_SIZE = 128
WORKERS = 8
LIMIT = None
MODELS = ["baseline", "resnet50_full", "resnet50_frozen"]

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
AMP = DEVICE.type == "cuda"

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406]).reshape(1, 1, 3)
IMAGENET_STD = np.array([0.229, 0.224, 0.225]).reshape(1, 1, 3)

RESULTS_DIR = REPO_ROOT / "assignment2" / "results"
CHECKPOINT_DIR = REPO_ROOT / "assignment2" / "checkpoints"
HISTORY_DIR = RESULTS_DIR / "history"
CURVES_DIR = RESULTS_DIR / "curves"
EXAMPLES_DIR = RESULTS_DIR / "examples"
CONFUSION_DIR = RESULTS_DIR / "confusion"

for directory in (RESULTS_DIR, CHECKPOINT_DIR, HISTORY_DIR, CURVES_DIR, EXAMPLES_DIR, CONFUSION_DIR):
    directory.mkdir(parents=True, exist_ok=True)

print("device:", DEVICE)

device: cuda

In [2]:
loaders, class_names = build_food101_loaders(
    128, batch_size=8, workers=0, limit=16, seed=SPLIT_SEED
)
images, labels = next(iter(loaders["train"]))
print("classes:", len(class_names))
print("batch:", tuple(images.shape), images.dtype)
print("labels:", labels[:8].tolist())

classes: 101
batch: (8, 3, 128, 128) torch.float32
labels: [26, 76, 60, 7, 46, 13, 34, 92]

In [3]:
def build_model(name, num_classes, image_size):
    if name == "baseline":
        return build_baseline_cnn(num_classes=num_classes, image_size=image_size)
    if name == "resnet50_full":
        return build_resnet50(num_classes=num_classes, pretrained=True, freeze_backbone=False)
    if name == "resnet50_frozen":
        return build_resnet50(num_classes=num_classes, pretrained=True, freeze_backbone=True)
    raise ValueError(f"unknown model: {name}")

In [4]:
def top_confusions(cm, class_names, k=20):
    pairs = []
    for true_index in range(cm.shape[0]):
        for predicted_index in range(cm.shape[1]):
            if true_index == predicted_index:
                continue
            count = int(cm[true_index, predicted_index])
            if count:
                pairs.append((class_names[true_index], class_names[predicted_index], count))
    return sorted(pairs, key=lambda item: item[2], reverse=True)[:k]


def plot_top_confusions(pairs, path, title):
    if not pairs:
        return
    labels = [f"{true} -> {predicted}" for true, predicted, _ in pairs]
    counts = [count for _, _, count in pairs]

    fig, ax = plt.subplots(figsize=(10, 0.35 * len(pairs)))
    ax.barh(labels[::-1], counts[::-1], color="#0366d6")
    ax.set_xlabel("test images")
    ax.set_title(title)
    ax.grid(axis="x", alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def predict(model, loader, device, amp=True):
    model.eval()
    predictions, targets = [], []
    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device, non_blocking=True)
            with torch.amp.autocast("cuda", enabled=amp):
                logits = model(images)
            predictions.append(logits.argmax(1).cpu())
            targets.append(labels)
    return torch.cat(predictions).numpy(), torch.cat(targets).numpy()

## Controlled experiment: freeze vs full fine-tune

- Hypothesis: full fine-tuning beats a frozen backbone.
- Changed factor: backbone frozen vs fully trainable.
- Fixed factors: data split, augmentation, input size, epochs, optimizer, batch size, seeds.
- Metrics: test accuracy, macro-F1, training time, inference time.

In [5]:
results = []
histories = {}
per_class_metrics = {}
confusion_pairs = {}

for seed in SEEDS:
    for name in MODELS:
        print(f"\n=== {name} | seed {seed} ===")
        set_seed(seed)
        image_size = 128 if name == "baseline" else 224
        loaders, class_names = build_food101_loaders(
            image_size,
            batch_size=BATCH_SIZE,
            workers=WORKERS,
            limit=LIMIT,
            seed=SPLIT_SEED,
        )
        model = build_model(name, len(class_names), image_size).to(DEVICE)
        frozen = name == "resnet50_frozen"
        params = sum(p.numel() for p in model.parameters())
        trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
        checkpoint_path = CHECKPOINT_DIR / f"{name}_seed{seed}.pt"

        history, best_epoch, train_time = fit(
            model,
            loaders,
            DEVICE,
            epochs=EPOCHS,
            lr=1e-4 if name.startswith("resnet") else 1e-3,
            weight_decay=1e-4,
            amp=AMP,
            checkpoint_path=checkpoint_path,
            frozen_backbone=frozen,
            seed=seed,
        )

        test = evaluate(model, loaders["test"], nn.CrossEntropyLoss(), DEVICE, AMP)
        inference_time, inference_ms = measure_inference_time(model, loaders["test"], DEVICE)
        predictions, targets = predict(model, loaders["test"], DEVICE, AMP)

        cm = confusion_matrix(targets, predictions, labels=np.arange(len(class_names)))
        precision, recall, f1, support = precision_recall_fscore_support(
            targets,
            predictions,
            labels=np.arange(len(class_names)),
            average=None,
            zero_division=0,
        )
        pairs = top_confusions(cm, class_names)

        run_name = f"{name}_seed{seed}"
        histories[run_name] = history
        per_class_metrics[run_name] = [
            {
                "class_id": index,
                "class_name": class_names[index],
                "precision": float(precision[index]),
                "recall": float(recall[index]),
                "f1": float(f1[index]),
                "support": int(support[index]),
            }
            for index in range(len(class_names))
        ]
        confusion_pairs[run_name] = [
            {"true": true, "predicted": predicted, "count": count}
            for true, predicted, count in pairs
        ]

        with open(HISTORY_DIR / f"{run_name}.json", "w") as handle:
            json.dump(history, handle, indent=2)
        with open(CONFUSION_DIR / f"{run_name}_top_confusions.json", "w") as handle:
            json.dump(confusion_pairs[run_name], handle, indent=2)
        np.save(CONFUSION_DIR / f"{run_name}.npy", cm)

        plot_curves(history, CURVES_DIR / f"{run_name}.png", run_name)
        plot_top_confusions(pairs, CONFUSION_DIR / f"{run_name}_top_confusions.png", run_name)

        example_images, example_labels = next(iter(loaders["test"]))
        with torch.no_grad():
            with torch.amp.autocast("cuda", enabled=AMP):
                example_logits = model(example_images.to(DEVICE))
        example_predictions = example_logits.argmax(1).cpu().numpy()
        plot_examples(
            example_images,
            example_labels.numpy(),
            example_predictions,
            class_names,
            EXAMPLES_DIR / f"{run_name}.png",
            run_name,
            IMAGENET_MEAN,
            IMAGENET_STD,
        )

        results.append(
            {
                "model": name,
                "seed": seed,
                "params": params,
                "trainable_params": trainable,
                "image_size": image_size,
                "best_epoch": best_epoch,
                "train_time_s": train_time,
                "inference_time_s": inference_time,
                "inference_ms_per_sample": inference_ms,
                "val_accuracy": history["validation_accuracy"][best_epoch - 1],
                "val_macro_f1": history["validation_macro_f1"][best_epoch - 1],
                "test_accuracy": test["accuracy"],
                "test_macro_f1": test["macro_f1"],
            }
        )

        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

results_df = pd.DataFrame(results)
results_df

=== baseline | seed 42 ===

epoch 01/30 | train loss 4.2091 acc 0.0663 | val loss 3.8797 acc 0.1100 macro-F1 0.0878 | 32.9s

epoch 02/30 | train loss 3.7268 acc 0.1391 | val loss 3.5614 acc 0.1646 macro-F1 0.1393 | 32.0s

epoch 03/30 | train loss 3.4180 acc 0.1938 | val loss 3.3553 acc 0.2038 macro-F1 0.1841 | 30.4s

epoch 04/30 | train loss 3.2091 acc 0.2320 | val loss 3.1648 acc 0.2384 macro-F1 0.2190 | 30.3s

epoch 05/30 | train loss 3.0382 acc 0.2664 | val loss 3.0910 acc 0.2532 macro-F1 0.2365 | 30.4s

epoch 06/30 | train loss 2.9050 acc 0.2928 | val loss 3.0285 acc 0.2618 macro-F1 0.2476 | 28.9s

epoch 07/30 | train loss 2.7964 acc 0.3127 | val loss 2.9664 acc 0.2785 macro-F1 0.2639 | 30.0s

epoch 08/30 | train loss 2.7044 acc 0.3314 | val loss 2.8930 acc 0.2948 macro-F1 0.2867 | 30.9s

epoch 09/30 | train loss 2.6197 acc 0.3501 | val loss 2.9318 acc 0.2978 macro-F1 0.2832 | 29.2s

epoch 10/30 | train loss 2.5548 acc 0.3621 | val loss 2.9200 acc 0.3007 macro-F1 0.2845 | 29.9s

epoch 11/30 | train loss 2.4776 acc 0.3770 | val loss 2.8672 acc 0.3094 macro-F1 0.2992 | 31.0s

epoch 12/30 | train loss 2.4114 acc 0.3922 | val loss 2.8088 acc 0.3168 macro-F1 0.3076 | 31.0s

epoch 13/30 | train loss 2.3506 acc 0.4064 | val loss 2.8233 acc 0.3267 macro-F1 0.3158 | 31.0s

epoch 14/30 | train loss 2.2893 acc 0.4181 | val loss 2.9098 acc 0.3109 macro-F1 0.3037 | 30.2s

epoch 15/30 | train loss 2.2410 acc 0.4280 | val loss 2.8768 acc 0.3179 macro-F1 0.3120 | 29.8s

epoch 16/30 | train loss 2.1863 acc 0.4395 | val loss 2.8363 acc 0.3258 macro-F1 0.3133 | 30.1s

epoch 17/30 | train loss 2.1423 acc 0.4496 | val loss 2.8176 acc 0.3307 macro-F1 0.3217 | 28.9s

epoch 18/30 | train loss 2.0829 acc 0.4641 | val loss 2.8969 acc 0.3281 macro-F1 0.3235 | 28.9s

epoch 19/30 | train loss 2.0450 acc 0.4715 | val loss 2.8311 acc 0.3350 macro-F1 0.3272 | 29.1s

epoch 20/30 | train loss 2.0066 acc 0.4799 | val loss 2.8771 acc 0.3340 macro-F1 0.3248 | 30.1s

epoch 21/30 | train loss 1.9774 acc 0.4850 | val loss 2.8679 acc 0.3279 macro-F1 0.3231 | 29.7s

epoch 22/30 | train loss 1.9266 acc 0.4985 | val loss 2.9191 acc 0.3236 macro-F1 0.3193 | 30.5s

epoch 23/30 | train loss 1.8974 acc 0.5047 | val loss 2.9053 acc 0.3304 macro-F1 0.3269 | 30.4s

epoch 24/30 | train loss 1.8575 acc 0.5130 | val loss 2.9482 acc 0.3314 macro-F1 0.3255 | 29.9s

epoch 25/30 | train loss 1.8194 acc 0.5214 | val loss 2.9406 acc 0.3319 macro-F1 0.3274 | 29.4s

epoch 26/30 | train loss 1.7904 acc 0.5289 | val loss 2.9302 acc 0.3424 macro-F1 0.3356 | 31.3s

epoch 27/30 | train loss 1.7641 acc 0.5356 | val loss 2.9456 acc 0.3370 macro-F1 0.3317 | 29.2s

epoch 28/30 | train loss 1.7289 acc 0.5441 | val loss 3.0284 acc 0.3323 macro-F1 0.3280 | 30.7s

epoch 29/30 | train loss 1.6951 acc 0.5530 | val loss 3.0229 acc 0.3279 macro-F1 0.3218 | 30.2s

epoch 30/30 | train loss 1.6777 acc 0.5534 | val loss 2.9838 acc 0.3340 macro-F1 0.3299 | 30.2s

=== resnet50_full | seed 42 ===

epoch 01/30 | train loss 1.9271 acc 0.5572 | val loss 1.0407 acc 0.7299 macro-F1 0.7279 | 71.0s

epoch 02/30 | train loss 0.8270 acc 0.7810 | val loss 0.8649 acc 0.7637 macro-F1 0.7619 | 59.7s

epoch 03/30 | train loss 0.5924 acc 0.8393 | val loss 0.7917 acc 0.7896 macro-F1 0.7884 | 89.3s

epoch 04/30 | train loss 0.4491 acc 0.8758 | val loss 0.7625 acc 0.8042 macro-F1 0.8032 | 58.5s

epoch 05/30 | train loss 0.3401 acc 0.9053 | val loss 0.7676 acc 0.8012 macro-F1 0.8005 | 60.7s

epoch 06/30 | train loss 0.2600 acc 0.9261 | val loss 0.7962 acc 0.8016 macro-F1 0.8005 | 62.8s

epoch 07/30 | train loss 0.2043 acc 0.9429 | val loss 0.8218 acc 0.7958 macro-F1 0.7947 | 71.3s

epoch 08/30 | train loss 0.1656 acc 0.9529 | val loss 0.8274 acc 0.7999 macro-F1 0.7993 | 58.0s

epoch 09/30 | train loss 0.1322 acc 0.9624 | val loss 0.8828 acc 0.7991 macro-F1 0.7986 | 67.1s

epoch 10/30 | train loss 0.1092 acc 0.9685 | val loss 0.9286 acc 0.7935 macro-F1 0.7919 | 61.4s

epoch 11/30 | train loss 0.0965 acc 0.9723 | val loss 0.9189 acc 0.8004 macro-F1 0.7997 | 62.2s

epoch 12/30 | train loss 0.0893 acc 0.9734 | val loss 0.9301 acc 0.8001 macro-F1 0.8006 | 60.0s

epoch 13/30 | train loss 0.0807 acc 0.9766 | val loss 0.9575 acc 0.7996 macro-F1 0.7991 | 63.2s

epoch 14/30 | train loss 0.0758 acc 0.9769 | val loss 0.9733 acc 0.7980 macro-F1 0.7988 | 66.4s

epoch 15/30 | train loss 0.0691 acc 0.9793 | val loss 0.9639 acc 0.8024 macro-F1 0.8019 | 64.8s

epoch 16/30 | train loss 0.0649 acc 0.9803 | val loss 1.0104 acc 0.7938 macro-F1 0.7937 | 61.0s

epoch 17/30 | train loss 0.0613 acc 0.9816 | val loss 0.9998 acc 0.7949 macro-F1 0.7950 | 61.5s

epoch 18/30 | train loss 0.0576 acc 0.9828 | val loss 1.0105 acc 0.7926 macro-F1 0.7913 | 66.1s

epoch 19/30 | train loss 0.0582 acc 0.9827 | val loss 0.9965 acc 0.7913 macro-F1 0.7899 | 65.9s

epoch 20/30 | train loss 0.0512 acc 0.9850 | val loss 1.0255 acc 0.7984 macro-F1 0.7987 | 56.6s

epoch 21/30 | train loss 0.0533 acc 0.9841 | val loss 0.9965 acc 0.7972 macro-F1 0.7972 | 76.1s

epoch 22/30 | train loss 0.0481 acc 0.9854 | val loss 1.0364 acc 0.7971 macro-F1 0.7968 | 73.9s

epoch 23/30 | train loss 0.0483 acc 0.9846 | val loss 1.0377 acc 0.7959 macro-F1 0.7953 | 89.0s

epoch 24/30 | train loss 0.0464 acc 0.9858 | val loss 1.0590 acc 0.7946 macro-F1 0.7937 | 85.4s

epoch 25/30 | train loss 0.0458 acc 0.9863 | val loss 1.0199 acc 0.8007 macro-F1 0.7999 | 55.8s

epoch 26/30 | train loss 0.0438 acc 0.9865 | val loss 1.0550 acc 0.7962 macro-F1 0.7961 | 52.0s

epoch 27/30 | train loss 0.0428 acc 0.9871 | val loss 1.0561 acc 0.7975 macro-F1 0.7974 | 54.2s

epoch 28/30 | train loss 0.0365 acc 0.9890 | val loss 1.0786 acc 0.7962 macro-F1 0.7952 | 69.7s

epoch 29/30 | train loss 0.0444 acc 0.9863 | val loss 1.0685 acc 0.7980 macro-F1 0.7970 | 52.5s

epoch 30/30 | train loss 0.0397 acc 0.9880 | val loss 1.0482 acc 0.7993 macro-F1 0.7988 | 78.2s

=== resnet50_frozen | seed 42 ===

epoch 01/30 | train loss 4.1280 acc 0.2708 | val loss 3.7131 acc 0.4343 macro-F1 0.4159 | 49.2s

epoch 02/30 | train loss 3.4104 acc 0.4811 | val loss 3.1491 acc 0.5038 macro-F1 0.4858 | 42.6s

epoch 03/30 | train loss 2.9367 acc 0.5288 | val loss 2.7687 acc 0.5317 macro-F1 0.5144 | 39.6s

epoch 04/30 | train loss 2.6083 acc 0.5543 | val loss 2.5006 acc 0.5465 macro-F1 0.5305 | 39.9s

epoch 05/30 | train loss 2.3696 acc 0.5697 | val loss 2.3038 acc 0.5593 macro-F1 0.5452 | 42.5s

epoch 06/30 | train loss 2.1914 acc 0.5824 | val loss 2.1549 acc 0.5702 macro-F1 0.5574 | 40.7s

epoch 07/30 | train loss 2.0538 acc 0.5912 | val loss 2.0391 acc 0.5803 macro-F1 0.5691 | 38.1s

epoch 08/30 | train loss 1.9434 acc 0.6030 | val loss 1.9468 acc 0.5868 macro-F1 0.5762 | 37.3s

epoch 09/30 | train loss 1.8559 acc 0.6087 | val loss 1.8716 acc 0.5934 macro-F1 0.5838 | 57.1s

epoch 10/30 | train loss 1.7807 acc 0.6181 | val loss 1.8096 acc 0.6004 macro-F1 0.5912 | 38.5s

epoch 11/30 | train loss 1.7184 acc 0.6241 | val loss 1.7576 acc 0.6046 macro-F1 0.5962 | 49.3s

epoch 12/30 | train loss 1.6675 acc 0.6299 | val loss 1.7136 acc 0.6083 macro-F1 0.6000 | 39.2s

epoch 13/30 | train loss 1.6183 acc 0.6354 | val loss 1.6756 acc 0.6123 macro-F1 0.6043 | 38.5s

epoch 14/30 | train loss 1.5778 acc 0.6398 | val loss 1.6421 acc 0.6169 macro-F1 0.6097 | 56.9s

epoch 15/30 | train loss 1.5427 acc 0.6450 | val loss 1.6135 acc 0.6203 macro-F1 0.6132 | 38.4s

epoch 16/30 | train loss 1.5110 acc 0.6494 | val loss 1.5875 acc 0.6250 macro-F1 0.6183 | 46.3s

epoch 17/30 | train loss 1.4813 acc 0.6531 | val loss 1.5647 acc 0.6268 macro-F1 0.6207 | 54.3s

epoch 18/30 | train loss 1.4559 acc 0.6561 | val loss 1.5443 acc 0.6294 macro-F1 0.6238 | 40.0s

epoch 19/30 | train loss 1.4288 acc 0.6634 | val loss 1.5258 acc 0.6306 macro-F1 0.6247 | 42.7s

epoch 20/30 | train loss 1.4076 acc 0.6650 | val loss 1.5090 acc 0.6319 macro-F1 0.6265 | 37.4s

epoch 21/30 | train loss 1.3874 acc 0.6680 | val loss 1.4936 acc 0.6331 macro-F1 0.6279 | 52.5s

epoch 22/30 | train loss 1.3686 acc 0.6704 | val loss 1.4797 acc 0.6366 macro-F1 0.6316 | 45.2s

epoch 23/30 | train loss 1.3512 acc 0.6757 | val loss 1.4667 acc 0.6384 macro-F1 0.6331 | 43.5s

epoch 24/30 | train loss 1.3321 acc 0.6785 | val loss 1.4554 acc 0.6418 macro-F1 0.6367 | 41.9s

epoch 25/30 | train loss 1.3189 acc 0.6802 | val loss 1.4437 acc 0.6409 macro-F1 0.6364 | 51.4s

epoch 26/30 | train loss 1.3034 acc 0.6824 | val loss 1.4340 acc 0.6432 macro-F1 0.6382 | 41.7s

epoch 27/30 | train loss 1.2874 acc 0.6858 | val loss 1.4244 acc 0.6449 macro-F1 0.6404 | 37.6s

epoch 28/30 | train loss 1.2744 acc 0.6875 | val loss 1.4158 acc 0.6463 macro-F1 0.6422 | 38.3s

epoch 29/30 | train loss 1.2640 acc 0.6893 | val loss 1.4069 acc 0.6475 macro-F1 0.6434 | 54.0s

epoch 30/30 | train loss 1.2501 acc 0.6929 | val loss 1.3993 acc 0.6492 macro-F1 0.6453 | 43.9s

=== baseline | seed 67 ===

epoch 01/30 | train loss 4.2340 acc 0.0627 | val loss 3.8464 acc 0.1150 macro-F1 0.0859 | 29.2s

epoch 02/30 | train loss 3.6573 acc 0.1514 | val loss 3.4125 acc 0.1938 macro-F1 0.1725 | 28.9s

epoch 03/30 | train loss 3.3172 acc 0.2130 | val loss 3.2490 acc 0.2206 macro-F1 0.2027 | 27.9s

epoch 04/30 | train loss 3.0870 acc 0.2554 | val loss 3.0556 acc 0.2613 macro-F1 0.2451 | 28.9s

epoch 05/30 | train loss 2.9318 acc 0.2840 | val loss 2.9865 acc 0.2755 macro-F1 0.2594 | 27.2s

epoch 06/30 | train loss 2.8061 acc 0.3097 | val loss 2.9383 acc 0.2817 macro-F1 0.2688 | 27.3s

epoch 07/30 | train loss 2.6858 acc 0.3335 | val loss 2.8796 acc 0.3005 macro-F1 0.2853 | 32.6s

epoch 08/30 | train loss 2.5870 acc 0.3562 | val loss 2.7886 acc 0.3205 macro-F1 0.3088 | 28.7s

epoch 09/30 | train loss 2.5019 acc 0.3739 | val loss 2.7322 acc 0.3298 macro-F1 0.3172 | 30.5s

epoch 10/30 | train loss 2.4221 acc 0.3906 | val loss 2.7237 acc 0.3347 macro-F1 0.3233 | 28.6s

epoch 11/30 | train loss 2.3527 acc 0.4053 | val loss 2.7049 acc 0.3464 macro-F1 0.3373 | 28.2s

epoch 12/30 | train loss 2.2834 acc 0.4212 | val loss 2.6918 acc 0.3455 macro-F1 0.3388 | 29.9s

epoch 13/30 | train loss 2.2235 acc 0.4328 | val loss 2.7030 acc 0.3439 macro-F1 0.3341 | 29.4s

epoch 14/30 | train loss 2.1689 acc 0.4471 | val loss 2.7723 acc 0.3424 macro-F1 0.3380 | 28.8s

epoch 15/30 | train loss 2.1144 acc 0.4572 | val loss 2.7020 acc 0.3488 macro-F1 0.3416 | 30.2s

epoch 16/30 | train loss 2.0629 acc 0.4677 | val loss 2.7217 acc 0.3529 macro-F1 0.3477 | 29.5s

epoch 17/30 | train loss 2.0160 acc 0.4783 | val loss 2.7370 acc 0.3514 macro-F1 0.3463 | 28.3s

epoch 18/30 | train loss 1.9794 acc 0.4862 | val loss 2.7491 acc 0.3546 macro-F1 0.3461 | 28.8s

epoch 19/30 | train loss 1.9283 acc 0.4975 | val loss 2.7920 acc 0.3383 macro-F1 0.3338 | 30.2s

epoch 20/30 | train loss 1.8926 acc 0.5053 | val loss 2.7384 acc 0.3564 macro-F1 0.3510 | 31.5s

epoch 21/30 | train loss 1.8577 acc 0.5143 | val loss 2.7875 acc 0.3506 macro-F1 0.3456 | 31.6s

epoch 22/30 | train loss 1.8187 acc 0.5230 | val loss 2.7615 acc 0.3509 macro-F1 0.3438 | 33.5s

epoch 23/30 | train loss 1.7890 acc 0.5304 | val loss 2.7702 acc 0.3659 macro-F1 0.3586 | 39.1s

epoch 24/30 | train loss 1.7578 acc 0.5346 | val loss 2.7765 acc 0.3601 macro-F1 0.3540 | 33.0s

epoch 25/30 | train loss 1.7191 acc 0.5444 | val loss 2.7938 acc 0.3691 macro-F1 0.3648 | 37.3s

epoch 26/30 | train loss 1.6883 acc 0.5523 | val loss 2.9102 acc 0.3485 macro-F1 0.3413 | 30.7s

epoch 27/30 | train loss 1.6537 acc 0.5614 | val loss 2.8611 acc 0.3571 macro-F1 0.3522 | 28.9s

epoch 28/30 | train loss 1.6293 acc 0.5673 | val loss 2.9108 acc 0.3611 macro-F1 0.3569 | 31.6s

epoch 29/30 | train loss 1.6090 acc 0.5734 | val loss 2.9139 acc 0.3566 macro-F1 0.3530 | 31.0s

epoch 30/30 | train loss 1.5669 acc 0.5826 | val loss 3.0001 acc 0.3443 macro-F1 0.3410 | 29.3s

=== resnet50_full | seed 67 ===

epoch 01/30 | train loss 1.9566 acc 0.5497 | val loss 1.0589 acc 0.7230 macro-F1 0.7202 | 57.3s

epoch 02/30 | train loss 0.8339 acc 0.7787 | val loss 0.8659 acc 0.7702 macro-F1 0.7688 | 65.6s

epoch 03/30 | train loss 0.5998 acc 0.8375 | val loss 0.7882 acc 0.7896 macro-F1 0.7896 | 52.3s

epoch 04/30 | train loss 0.4485 acc 0.8772 | val loss 0.7705 acc 0.7919 macro-F1 0.7906 | 53.2s

epoch 05/30 | train loss 0.3434 acc 0.9036 | val loss 0.7769 acc 0.7974 macro-F1 0.7967 | 62.3s

epoch 06/30 | train loss 0.2662 acc 0.9258 | val loss 0.7876 acc 0.7985 macro-F1 0.7981 | 59.3s

epoch 07/30 | train loss 0.2020 acc 0.9418 | val loss 0.8400 acc 0.7974 macro-F1 0.7974 | 50.7s

epoch 08/30 | train loss 0.1655 acc 0.9523 | val loss 0.8260 acc 0.8032 macro-F1 0.8022 | 50.8s

epoch 09/30 | train loss 0.1365 acc 0.9607 | val loss 0.8681 acc 0.8049 macro-F1 0.8053 | 51.3s

epoch 10/30 | train loss 0.1145 acc 0.9670 | val loss 0.8854 acc 0.7976 macro-F1 0.7970 | 54.9s

epoch 11/30 | train loss 0.0979 acc 0.9714 | val loss 0.9009 acc 0.7993 macro-F1 0.7989 | 51.2s

epoch 12/30 | train loss 0.0847 acc 0.9752 | val loss 0.9166 acc 0.8003 macro-F1 0.8006 | 53.5s

epoch 13/30 | train loss 0.0808 acc 0.9754 | val loss 0.9537 acc 0.7951 macro-F1 0.7945 | 53.2s

epoch 14/30 | train loss 0.0722 acc 0.9786 | val loss 0.9457 acc 0.7991 macro-F1 0.7988 | 50.8s

epoch 15/30 | train loss 0.0669 acc 0.9809 | val loss 0.9710 acc 0.7971 macro-F1 0.7969 | 51.8s

epoch 16/30 | train loss 0.0665 acc 0.9809 | val loss 0.9839 acc 0.7930 macro-F1 0.7925 | 51.2s

epoch 17/30 | train loss 0.0584 acc 0.9829 | val loss 0.9912 acc 0.7943 macro-F1 0.7943 | 51.7s

epoch 18/30 | train loss 0.0574 acc 0.9828 | val loss 1.0075 acc 0.7987 macro-F1 0.7983 | 52.1s

epoch 19/30 | train loss 0.0574 acc 0.9825 | val loss 1.0257 acc 0.7955 macro-F1 0.7948 | 51.1s

epoch 20/30 | train loss 0.0578 acc 0.9821 | val loss 1.0130 acc 0.7922 macro-F1 0.7909 | 52.1s

epoch 21/30 | train loss 0.0507 acc 0.9838 | val loss 1.0373 acc 0.7958 macro-F1 0.7953 | 51.9s

epoch 22/30 | train loss 0.0487 acc 0.9853 | val loss 1.0414 acc 0.7984 macro-F1 0.7973 | 50.6s

epoch 23/30 | train loss 0.0458 acc 0.9865 | val loss 1.0351 acc 0.7938 macro-F1 0.7936 | 51.8s

epoch 24/30 | train loss 0.0441 acc 0.9864 | val loss 1.0583 acc 0.7979 macro-F1 0.7974 | 50.9s

epoch 25/30 | train loss 0.0458 acc 0.9865 | val loss 1.0505 acc 0.7943 macro-F1 0.7942 | 52.3s

epoch 26/30 | train loss 0.0444 acc 0.9859 | val loss 1.0834 acc 0.7898 macro-F1 0.7901 | 50.6s

epoch 27/30 | train loss 0.0434 acc 0.9863 | val loss 1.0805 acc 0.7995 macro-F1 0.7978 | 50.8s

epoch 28/30 | train loss 0.0457 acc 0.9857 | val loss 1.0881 acc 0.7958 macro-F1 0.7958 | 55.3s

epoch 29/30 | train loss 0.0402 acc 0.9878 | val loss 1.0743 acc 0.7992 macro-F1 0.7985 | 55.5s

epoch 30/30 | train loss 0.0360 acc 0.9889 | val loss 1.0722 acc 0.8029 macro-F1 0.8028 | 54.5s

=== resnet50_frozen | seed 67 ===

epoch 01/30 | train loss 4.1399 acc 0.2575 | val loss 3.7243 acc 0.4318 macro-F1 0.4160 | 39.4s

epoch 02/30 | train loss 3.4181 acc 0.4818 | val loss 3.1561 acc 0.4987 macro-F1 0.4808 | 38.1s

epoch 03/30 | train loss 2.9420 acc 0.5268 | val loss 2.7727 acc 0.5298 macro-F1 0.5134 | 41.8s

epoch 04/30 | train loss 2.6112 acc 0.5524 | val loss 2.5030 acc 0.5459 macro-F1 0.5305 | 36.6s

epoch 05/30 | train loss 2.3723 acc 0.5707 | val loss 2.3059 acc 0.5603 macro-F1 0.5460 | 41.1s

epoch 06/30 | train loss 2.1922 acc 0.5828 | val loss 2.1560 acc 0.5690 macro-F1 0.5567 | 48.8s

epoch 07/30 | train loss 2.0562 acc 0.5916 | val loss 2.0397 acc 0.5793 macro-F1 0.5679 | 40.6s

epoch 08/30 | train loss 1.9428 acc 0.6023 | val loss 1.9466 acc 0.5889 macro-F1 0.5781 | 41.9s

epoch 09/30 | train loss 1.8567 acc 0.6091 | val loss 1.8716 acc 0.5943 macro-F1 0.5847 | 51.5s

epoch 10/30 | train loss 1.7808 acc 0.6177 | val loss 1.8100 acc 0.5980 macro-F1 0.5887 | 36.2s

epoch 11/30 | train loss 1.7197 acc 0.6241 | val loss 1.7581 acc 0.6044 macro-F1 0.5961 | 35.7s

epoch 12/30 | train loss 1.6670 acc 0.6294 | val loss 1.7136 acc 0.6091 macro-F1 0.6015 | 36.1s

epoch 13/30 | train loss 1.6207 acc 0.6348 | val loss 1.6755 acc 0.6119 macro-F1 0.6044 | 37.1s

epoch 14/30 | train loss 1.5772 acc 0.6410 | val loss 1.6428 acc 0.6160 macro-F1 0.6089 | 36.2s

epoch 15/30 | train loss 1.5414 acc 0.6447 | val loss 1.6134 acc 0.6195 macro-F1 0.6130 | 47.3s

epoch 16/30 | train loss 1.5102 acc 0.6501 | val loss 1.5877 acc 0.6227 macro-F1 0.6162 | 48.2s

epoch 17/30 | train loss 1.4821 acc 0.6542 | val loss 1.5649 acc 0.6251 macro-F1 0.6192 | 35.5s

epoch 18/30 | train loss 1.4537 acc 0.6584 | val loss 1.5447 acc 0.6277 macro-F1 0.6217 | 59.9s

epoch 19/30 | train loss 1.4315 acc 0.6602 | val loss 1.5258 acc 0.6286 macro-F1 0.6227 | 35.7s

epoch 20/30 | train loss 1.4068 acc 0.6657 | val loss 1.5093 acc 0.6333 macro-F1 0.6279 | 56.2s

epoch 21/30 | train loss 1.3873 acc 0.6680 | val loss 1.4933 acc 0.6337 macro-F1 0.6281 | 38.8s

epoch 22/30 | train loss 1.3688 acc 0.6710 | val loss 1.4793 acc 0.6366 macro-F1 0.6311 | 39.7s

epoch 23/30 | train loss 1.3529 acc 0.6742 | val loss 1.4667 acc 0.6379 macro-F1 0.6329 | 51.5s

epoch 24/30 | train loss 1.3342 acc 0.6774 | val loss 1.4544 acc 0.6392 macro-F1 0.6343 | 36.6s

epoch 25/30 | train loss 1.3185 acc 0.6793 | val loss 1.4438 acc 0.6415 macro-F1 0.6368 | 35.4s

epoch 26/30 | train loss 1.3030 acc 0.6821 | val loss 1.4334 acc 0.6425 macro-F1 0.6381 | 35.5s

epoch 27/30 | train loss 1.2899 acc 0.6857 | val loss 1.4241 acc 0.6450 macro-F1 0.6402 | 35.6s

epoch 28/30 | train loss 1.2735 acc 0.6899 | val loss 1.4157 acc 0.6466 macro-F1 0.6419 | 51.8s

epoch 29/30 | train loss 1.2636 acc 0.6888 | val loss 1.4076 acc 0.6473 macro-F1 0.6428 | 46.4s

epoch 30/30 | train loss 1.2513 acc 0.6915 | val loss 1.3994 acc 0.6506 macro-F1 0.6463 | 44.2s

=== baseline | seed 69 ===

epoch 01/30 | train loss 4.1922 acc 0.0687 | val loss 3.8604 acc 0.1139 macro-F1 0.0902 | 27.8s

epoch 02/30 | train loss 3.6366 acc 0.1541 | val loss 3.4133 acc 0.1925 macro-F1 0.1724 | 41.2s

epoch 03/30 | train loss 3.2895 acc 0.2152 | val loss 3.2197 acc 0.2239 macro-F1 0.2035 | 34.6s

epoch 04/30 | train loss 3.0383 acc 0.2627 | val loss 2.9888 acc 0.2686 macro-F1 0.2578 | 27.0s

epoch 05/30 | train loss 2.8537 acc 0.2987 | val loss 2.9154 acc 0.2854 macro-F1 0.2713 | 33.0s

epoch 06/30 | train loss 2.7147 acc 0.3309 | val loss 2.8653 acc 0.3014 macro-F1 0.2879 | 40.7s

epoch 07/30 | train loss 2.5950 acc 0.3560 | val loss 2.8077 acc 0.3126 macro-F1 0.3019 | 26.2s

epoch 08/30 | train loss 2.4957 acc 0.3760 | val loss 2.7095 acc 0.3283 macro-F1 0.3177 | 33.9s

epoch 09/30 | train loss 2.3965 acc 0.3977 | val loss 2.6514 acc 0.3423 macro-F1 0.3345 | 43.0s

epoch 10/30 | train loss 2.3297 acc 0.4109 | val loss 2.6599 acc 0.3488 macro-F1 0.3407 | 26.4s

epoch 11/30 | train loss 2.2569 acc 0.4264 | val loss 2.6399 acc 0.3578 macro-F1 0.3467 | 26.0s

epoch 12/30 | train loss 2.1859 acc 0.4418 | val loss 2.6262 acc 0.3547 macro-F1 0.3466 | 50.1s

epoch 13/30 | train loss 2.1285 acc 0.4567 | val loss 2.6123 acc 0.3615 macro-F1 0.3553 | 26.3s

epoch 14/30 | train loss 2.0765 acc 0.4649 | val loss 2.6157 acc 0.3625 macro-F1 0.3581 | 29.0s

epoch 15/30 | train loss 2.0225 acc 0.4752 | val loss 2.5924 acc 0.3749 macro-F1 0.3701 | 125.6s

epoch 16/30 | train loss 1.9811 acc 0.4865 | val loss 2.6062 acc 0.3815 macro-F1 0.3757 | 276.5s

epoch 17/30 | train loss 1.9288 acc 0.4969 | val loss 2.6307 acc 0.3673 macro-F1 0.3620 | 152.4s

epoch 18/30 | train loss 1.8854 acc 0.5099 | val loss 2.6173 acc 0.3787 macro-F1 0.3751 | 106.5s

epoch 19/30 | train loss 1.8488 acc 0.5177 | val loss 2.6957 acc 0.3723 macro-F1 0.3652 | 111.2s

epoch 20/30 | train loss 1.8154 acc 0.5237 | val loss 2.6194 acc 0.3736 macro-F1 0.3678 | 102.9s

epoch 21/30 | train loss 1.7674 acc 0.5343 | val loss 2.7161 acc 0.3793 macro-F1 0.3722 | 99.9s

epoch 22/30 | train loss 1.7426 acc 0.5405 | val loss 2.7187 acc 0.3719 macro-F1 0.3656 | 94.9s

epoch 23/30 | train loss 1.7152 acc 0.5469 | val loss 2.6746 acc 0.3770 macro-F1 0.3731 | 108.2s

epoch 24/30 | train loss 1.6719 acc 0.5577 | val loss 2.7414 acc 0.3744 macro-F1 0.3731 | 98.4s

epoch 25/30 | train loss 1.6421 acc 0.5635 | val loss 2.7689 acc 0.3733 macro-F1 0.3680 | 102.4s

epoch 26/30 | train loss 1.6107 acc 0.5728 | val loss 2.7439 acc 0.3747 macro-F1 0.3685 | 60.5s

epoch 27/30 | train loss 1.5953 acc 0.5748 | val loss 2.8480 acc 0.3729 macro-F1 0.3694 | 40.3s

epoch 28/30 | train loss 1.5722 acc 0.5780 | val loss 2.7462 acc 0.3749 macro-F1 0.3736 | 113.4s

epoch 29/30 | train loss 1.5426 acc 0.5874 | val loss 2.7973 acc 0.3761 macro-F1 0.3710 | 119.3s

epoch 30/30 | train loss 1.5131 acc 0.5949 | val loss 2.8245 acc 0.3815 macro-F1 0.3763 | 29.7s

=== resnet50_full | seed 69 ===

epoch 01/30 | train loss 1.9196 acc 0.5581 | val loss 1.0329 acc 0.7294 macro-F1 0.7277 | 52.5s

epoch 02/30 | train loss 0.8273 acc 0.7801 | val loss 0.8632 acc 0.7736 macro-F1 0.7730 | 51.0s

epoch 03/30 | train loss 0.5902 acc 0.8413 | val loss 0.7743 acc 0.7942 macro-F1 0.7948 | 50.8s

epoch 04/30 | train loss 0.4448 acc 0.8764 | val loss 0.7679 acc 0.8033 macro-F1 0.8030 | 50.6s

epoch 05/30 | train loss 0.3364 acc 0.9067 | val loss 0.7845 acc 0.8005 macro-F1 0.7998 | 50.8s

epoch 06/30 | train loss 0.2577 acc 0.9281 | val loss 0.8118 acc 0.7975 macro-F1 0.7980 | 50.7s

epoch 07/30 | train loss 0.2016 acc 0.9431 | val loss 0.8244 acc 0.7988 macro-F1 0.7985 | 50.7s

epoch 08/30 | train loss 0.1642 acc 0.9533 | val loss 0.8328 acc 0.7971 macro-F1 0.7968 | 50.9s

epoch 09/30 | train loss 0.1328 acc 0.9616 | val loss 0.8804 acc 0.7947 macro-F1 0.7937 | 50.5s

epoch 10/30 | train loss 0.1110 acc 0.9665 | val loss 0.9261 acc 0.7935 macro-F1 0.7944 | 50.3s

epoch 11/30 | train loss 0.0976 acc 0.9709 | val loss 0.9102 acc 0.8003 macro-F1 0.8006 | 50.4s

epoch 12/30 | train loss 0.0831 acc 0.9762 | val loss 0.9294 acc 0.7985 macro-F1 0.7979 | 50.2s

epoch 13/30 | train loss 0.0807 acc 0.9756 | val loss 0.9792 acc 0.7914 macro-F1 0.7912 | 50.4s

epoch 14/30 | train loss 0.0716 acc 0.9791 | val loss 0.9419 acc 0.7991 macro-F1 0.7978 | 50.5s

epoch 15/30 | train loss 0.0665 acc 0.9805 | val loss 0.9533 acc 0.7970 macro-F1 0.7957 | 50.3s

epoch 16/30 | train loss 0.0704 acc 0.9785 | val loss 0.9910 acc 0.7926 macro-F1 0.7916 | 50.2s

epoch 17/30 | train loss 0.0646 acc 0.9803 | val loss 1.0077 acc 0.7912 macro-F1 0.7911 | 50.4s

epoch 18/30 | train loss 0.0546 acc 0.9835 | val loss 1.0011 acc 0.8016 macro-F1 0.8008 | 50.1s

epoch 19/30 | train loss 0.0552 acc 0.9833 | val loss 1.0193 acc 0.7962 macro-F1 0.7956 | 50.4s

epoch 20/30 | train loss 0.0508 acc 0.9845 | val loss 1.0388 acc 0.7952 macro-F1 0.7943 | 50.5s

epoch 21/30 | train loss 0.0540 acc 0.9832 | val loss 1.0241 acc 0.7995 macro-F1 0.7997 | 50.2s

epoch 22/30 | train loss 0.0490 acc 0.9850 | val loss 1.0239 acc 0.8033 macro-F1 0.8030 | 50.4s

epoch 23/30 | train loss 0.0486 acc 0.9848 | val loss 1.0459 acc 0.7978 macro-F1 0.7966 | 50.5s

epoch 24/30 | train loss 0.0467 acc 0.9859 | val loss 1.0590 acc 0.7963 macro-F1 0.7963 | 50.8s

epoch 25/30 | train loss 0.0432 acc 0.9867 | val loss 1.0712 acc 0.7991 macro-F1 0.7982 | 50.7s

epoch 26/30 | train loss 0.0437 acc 0.9867 | val loss 1.0710 acc 0.7960 macro-F1 0.7961 | 50.4s

epoch 27/30 | train loss 0.0414 acc 0.9873 | val loss 1.0460 acc 0.7952 macro-F1 0.7952 | 50.4s

epoch 28/30 | train loss 0.0441 acc 0.9865 | val loss 1.0670 acc 0.7950 macro-F1 0.7936 | 50.2s

epoch 29/30 | train loss 0.0384 acc 0.9884 | val loss 1.0512 acc 0.8021 macro-F1 0.8013 | 50.3s

epoch 30/30 | train loss 0.0392 acc 0.9879 | val loss 1.0779 acc 0.7964 macro-F1 0.7958 | 50.4s

=== resnet50_frozen | seed 69 ===

epoch 01/30 | train loss 4.1313 acc 0.2694 | val loss 3.7161 acc 0.4368 macro-F1 0.4186 | 47.4s

epoch 02/30 | train loss 3.4133 acc 0.4812 | val loss 3.1494 acc 0.5009 macro-F1 0.4836 | 46.8s

epoch 03/30 | train loss 2.9361 acc 0.5272 | val loss 2.7682 acc 0.5284 macro-F1 0.5110 | 43.9s

epoch 04/30 | train loss 2.6083 acc 0.5533 | val loss 2.4993 acc 0.5486 macro-F1 0.5330 | 37.9s

epoch 05/30 | train loss 2.3707 acc 0.5691 | val loss 2.3030 acc 0.5600 macro-F1 0.5451 | 36.1s

epoch 06/30 | train loss 2.1909 acc 0.5817 | val loss 2.1538 acc 0.5712 macro-F1 0.5585 | 35.8s

epoch 07/30 | train loss 2.0536 acc 0.5926 | val loss 2.0379 acc 0.5810 macro-F1 0.5691 | 35.2s

epoch 08/30 | train loss 1.9447 acc 0.6015 | val loss 1.9459 acc 0.5872 macro-F1 0.5766 | 35.5s

epoch 09/30 | train loss 1.8555 acc 0.6093 | val loss 1.8707 acc 0.5927 macro-F1 0.5822 | 35.6s

epoch 10/30 | train loss 1.7810 acc 0.6175 | val loss 1.8092 acc 0.5991 macro-F1 0.5896 | 35.4s

epoch 11/30 | train loss 1.7190 acc 0.6246 | val loss 1.7567 acc 0.6025 macro-F1 0.5940 | 35.4s

epoch 12/30 | train loss 1.6655 acc 0.6290 | val loss 1.7125 acc 0.6077 macro-F1 0.5995 | 35.6s

epoch 13/30 | train loss 1.6197 acc 0.6348 | val loss 1.6745 acc 0.6123 macro-F1 0.6044 | 35.2s

epoch 14/30 | train loss 1.5790 acc 0.6401 | val loss 1.6421 acc 0.6165 macro-F1 0.6092 | 35.3s

epoch 15/30 | train loss 1.5421 acc 0.6449 | val loss 1.6129 acc 0.6174 macro-F1 0.6101 | 35.4s

epoch 16/30 | train loss 1.5095 acc 0.6495 | val loss 1.5870 acc 0.6227 macro-F1 0.6163 | 35.6s

epoch 17/30 | train loss 1.4819 acc 0.6533 | val loss 1.5645 acc 0.6265 macro-F1 0.6206 | 35.8s

epoch 18/30 | train loss 1.4542 acc 0.6574 | val loss 1.5433 acc 0.6279 macro-F1 0.6222 | 36.5s

epoch 19/30 | train loss 1.4316 acc 0.6613 | val loss 1.5252 acc 0.6294 macro-F1 0.6240 | 35.1s

epoch 20/30 | train loss 1.4080 acc 0.6650 | val loss 1.5087 acc 0.6304 macro-F1 0.6254 | 36.3s

epoch 21/30 | train loss 1.3892 acc 0.6683 | val loss 1.4934 acc 0.6334 macro-F1 0.6279 | 35.3s

epoch 22/30 | train loss 1.3677 acc 0.6715 | val loss 1.4787 acc 0.6356 macro-F1 0.6305 | 35.2s

epoch 23/30 | train loss 1.3496 acc 0.6755 | val loss 1.4658 acc 0.6379 macro-F1 0.6333 | 35.3s

epoch 24/30 | train loss 1.3311 acc 0.6777 | val loss 1.4542 acc 0.6404 macro-F1 0.6354 | 42.6s

epoch 25/30 | train loss 1.3165 acc 0.6805 | val loss 1.4432 acc 0.6400 macro-F1 0.6356 | 57.1s

epoch 26/30 | train loss 1.3030 acc 0.6829 | val loss 1.4331 acc 0.6426 macro-F1 0.6385 | 37.5s

epoch 27/30 | train loss 1.2863 acc 0.6861 | val loss 1.4235 acc 0.6444 macro-F1 0.6399 | 38.1s

epoch 28/30 | train loss 1.2742 acc 0.6888 | val loss 1.4144 acc 0.6474 macro-F1 0.6435 | 56.6s

epoch 29/30 | train loss 1.2629 acc 0.6896 | val loss 1.4064 acc 0.6477 macro-F1 0.6433 | 41.4s

epoch 30/30 | train loss 1.2502 acc 0.6911 | val loss 1.3990 acc 0.6484 macro-F1 0.6445 | 35.4s

,model,seed,params,trainable_params,image_size,best_epoch,train_time_s,inference_time_s,inference_ms_per_sample,val_accuracy,val_macro_f1,test_accuracy,test_macro_f1
0,baseline,42,8829349,8829349,128,26,907.341204,11.048900,0.437580,0.342442,0.335627,0.375525,0.369793
1,resnet50_full,42,23714981,23714981,224,4,1975.356891,15.463274,0.612407,0.804224,0.803177,0.840950,0.840223
2,resnet50_frozen,42,23714981,206949,224,30,1327.229693,15.001953,0.594137,0.649241,0.645334,0.693545,0.690529
3,baseline,67,8829349,8829349,128,25,911.756279,10.536974,0.417306,0.369109,0.364824,0.408079,0.404377
4,resnet50_full,67,23714981,23714981,224,9,1601.728559,16.903400,0.669442,0.804884,0.805273,0.842812,0.843165
5,resnet50_frozen,67,23714981,206949,224,30,1264.166588,20.652482,0.817920,0.650561,0.646340,0.692515,0.689113
6,baseline,69,8829349,8829349,128,30,2208.284280,9.917316,0.392765,0.381518,0.376326,0.421901,0.417937
7,resnet50_full,69,23714981,23714981,224,4,1517.238745,14.796757,0.586010,0.803300,0.802964,0.842218,0.842302
8,resnet50_frozen,69,23714981,206949,224,30,1164.539487,19.675198,0.779216,0.648449,0.644474,0.692673,0.689221

In [6]:
summary_spec = {
    "runs": ("seed", "count"),
    "test_accuracy_mean": ("test_accuracy", "mean"),
    "test_accuracy_std": ("test_accuracy", "std"),
    "test_macro_f1_mean": ("test_macro_f1", "mean"),
    "test_macro_f1_std": ("test_macro_f1", "std"),
    "val_accuracy_mean": ("val_accuracy", "mean"),
    "val_macro_f1_mean": ("val_macro_f1", "mean"),
    "best_epoch_mean": ("best_epoch", "mean"),
    "train_time_s_mean": ("train_time_s", "mean"),
    "inference_ms_per_sample_mean": ("inference_ms_per_sample", "mean"),
}

summary_df = results_df.groupby("model").agg(**summary_spec).reset_index()
summary_df

,model,runs,test_accuracy_mean,test_accuracy_std,test_macro_f1_mean,test_macro_f1_std,val_accuracy_mean,val_macro_f1_mean,best_epoch_mean,train_time_s_mean,inference_ms_per_sample_mean
0,baseline,3,0.401835,0.023810,0.397369,0.024825,0.364356,0.358926,27.000000,1342.460588,0.415884
1,resnet50_frozen,3,0.692911,0.000554,0.689621,0.000788,0.649417,0.645383,30.000000,1251.978589,0.730424
2,resnet50_full,3,0.841993,0.000951,0.841897,0.001512,0.804136,0.803805,5.666667,1698.108065,0.622620

In [7]:
ab = summary_df.set_index("model").loc[["resnet50_frozen", "resnet50_full"]]

ablation_summary = {
    "changed_factor": "frozen backbone vs full fine-tune",
    "hypothesis": "full fine-tuning beats a frozen backbone on Food-101",
    "seeds": SEEDS,
    "frozen_test_accuracy_mean": float(ab.loc["resnet50_frozen", "test_accuracy_mean"]),
    "full_test_accuracy_mean": float(ab.loc["resnet50_full", "test_accuracy_mean"]),
    "delta_test_accuracy": float(ab.loc["resnet50_full", "test_accuracy_mean"] - ab.loc["resnet50_frozen", "test_accuracy_mean"]),
    "frozen_test_macro_f1_mean": float(ab.loc["resnet50_frozen", "test_macro_f1_mean"]),
    "full_test_macro_f1_mean": float(ab.loc["resnet50_full", "test_macro_f1_mean"]),
    "delta_test_macro_f1": float(ab.loc["resnet50_full", "test_macro_f1_mean"] - ab.loc["resnet50_frozen", "test_macro_f1_mean"]),
    "decision_criterion": "compare the mean over the three seeds and the spread across seeds",
}
ablation_summary

{'changed_factor': 'frozen backbone vs full fine-tune',
 'hypothesis': 'full fine-tuning beats a frozen backbone on Food-101',
 'seeds': [42, 67, 69],
 'frozen_test_accuracy_mean': 0.692910891089109,
 'full_test_accuracy_mean': 0.841993399339934,
 'delta_test_accuracy': 0.14908250825082503,
 'frozen_test_macro_f1_mean': 0.6896207264202534,
 'full_test_macro_f1_mean': 0.8418965881373488,
 'delta_test_macro_f1': 0.1522758617170954,
 'decision_criterion': 'compare the mean over the three seeds and the spread across seeds'}

In [8]:
config = {
    "dataset": "food-101",
    "split_seed": SPLIT_SEED,
    "training_seeds": SEEDS,
    "epochs": EPOCHS,
    "batch_size": BATCH_SIZE,
    "limit": LIMIT,
    "amp": AMP,
    "monitor": "validation_macro_f1",
    "models": MODELS,
    "device": str(DEVICE),
    "torch_version": torch.__version__,
    "cuda_version": torch.version.cuda,
    "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
}

payload = {
    "config": config,
    "results": results,
    "summary": summary_df.to_dict(orient="records"),
    "ablation": ablation_summary,
    "history": histories,
    "per_class": per_class_metrics,
    "top_confusions": confusion_pairs,
}

results_df.to_csv(RESULTS_DIR / "results.csv", index=False)
summary_df.to_csv(RESULTS_DIR / "summary.csv", index=False)

with open(RESULTS_DIR / "results.json", "w") as handle:
    json.dump(payload, handle, indent=2)

print("saved", RESULTS_DIR / "results.json")

saved /raid/home/an.nv/main/deep-learning/CO3133-DeepLearning/assignment2/results/results.json

## Next steps

- Write the final A2 report, slides, and YouTube video.
- Link the final deliverables from `assignment2/index.html` and the landing page.